// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrYtsEcgmpNgtTENNID9CYdDgKER0OXs4',
    appId: '1:356596888356:web:cfea12ebd0671d475eb9b1',
    messagingSenderId: '356596888356',
    projectId: 'windows-proje-4416',
    authDomain: 'windows-proje-4416.firebaseapp.com',
    storageBucket: 'windows-proje-4416.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByo9s2RNlC3qFN-0E3kJI0FwBiwi-AghU',
    appId: '1:356596888356:android:d15c9345cd804b345eb9b1',
    messagingSenderId: '356596888356',
    projectId: 'windows-proje-4416',
    storageBucket: 'windows-proje-4416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0AGAY8HCHVnGxhZkZMkI8yz12o7TajPs',
    appId: '1:356596888356:ios:4bdeba47c24f07a45eb9b1',
    messagingSenderId: '356596888356',
    projectId: 'windows-proje-4416',
    storageBucket: 'windows-proje-4416.appspot.com',
    iosClientId: '356596888356-spa0jflnhflp36rigjjpvn9bcch3d0mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.msgapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0AGAY8HCHVnGxhZkZMkI8yz12o7TajPs',
    appId: '1:356596888356:ios:4bdeba47c24f07a45eb9b1',
    messagingSenderId: '356596888356',
    projectId: 'windows-proje-4416',
    storageBucket: 'windows-proje-4416.appspot.com',
    iosClientId: '356596888356-spa0jflnhflp36rigjjpvn9bcch3d0mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.msgapp',
  );
}
